"""storefront_content_fields

Revision ID: b53eba3c2fec
Revises: da52df67d271
Create Date: 2026-08-10 20:12:42.046384

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b53eba3c2fec"
down_revision: str | Sequence[str] | None = "da52df67d271"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tone",
                sa.Enum(
                    "GRAY",
                    "BRAND",
                    "DARK",
                    "KRAFT",
                    name="contenttone",
                    native_enum=False,
                    length=20,
                ),
                server_default="GRAY",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("show_in_navigation", sa.Boolean(), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column("is_highlighted", sa.Boolean(), server_default="0", nullable=False)
        )

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("delivery_days", sa.Integer(), server_default="3", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "tone",
                sa.Enum(
                    "GRAY",
                    "BRAND",
                    "DARK",
                    "KRAFT",
                    name="contenttone",
                    native_enum=False,
                    length=20,
                ),
                server_default="GRAY",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("tone")
        batch_op.drop_column("delivery_days")

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_column("is_highlighted")
        batch_op.drop_column("show_in_navigation")
        batch_op.drop_column("tone")

    # ### end Alembic commands ###
